title: "Ty's Books"
description: "A personal reading log"
baseurl: "/bookblog"
url: "https://tymatcha.github.io"

permalink: /books/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: book

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
